baseURL = "https://rootified.github.io/hugo-rootified/"
languageCode = "de-de"
title = "Der persönliche IT-Blog von Zen Sudo"
theme = "dimension"
description = "Aktuelle IT-Projekte, nützliche Tipps und persönliche Skripte für die macOS & Server Administration."

